#!/bin/bash

set -e

if [[ "${CI}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Sets up this project for development.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    # Build docker containers
    scripts/update

    # Bring up servers
    echo "Bringing up servers"
    scripts/server --detached

    echo "Done."

fi
