name: Planetary Computer APIs PR CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Set Azurite Default Key
        run: echo "AZURITE_ACCOUNT_KEY=$(curl https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azurite | grep "Account key:" | cut -b 24-111)" >> $GITHUB_ENV

      - name: Verify Azurite Key was retrieved correctly
        if: "!startsWith(env.AZURITE_ACCOUNT_KEY, 'Eby8')"
        run: echo Failed to find key at learn.microsoft.com && exit 1

      - name: Run cibuild
        run: ./scripts/cibuild

  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4
        with:
          python-version: "3.10" # stac-api-validator requires >= 3.10
          cache: "pip"

      - name: Set Azurite Default Key
        run: echo "AZURITE_ACCOUNT_KEY=$(curl https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azurite | grep "Account key:" | cut -b 24-111)" >> $GITHUB_ENV

      - name: API Validator
        run: ./scripts/validate
